apiVersion: v1
kind: Pod
metadata:
  name: redis
  label:
    type: redis
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname

  containers:
  - name: redis
    image: redis
