apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bear
  template:
    metadata:
      labels:
        app: bear
        type: app
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
