apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moose
  template:
    metadata:
      labels:
        app: moose
        type: app
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
