apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
    app.kubernetes.io/name: app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
