kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}
  labels:
{{- include "spring.labels" . | nindent 4}}
spec:
  selector:
    app: music    
  type: {{ .Values.type }}
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.target_port }}
