kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}
spec:
  container: 
    resources:
      requests:
        memory: {{ .Values.requests.memory }} 
        cpu: {{ .Values.requests.cpu }} 
      limits:
        memory: {{ .Values.limits.memory }} 
        cpu: {{ .Values.limits.cpu }} 
  selector:
    app: music    
  type: {{ .Values.type }}
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.target_port }}
